import cupi_quesos as c
def consola ():
    print ("Bienvenido Quesero")
    print ("Por favor seleccione que desea calcular")
    print ("1. costo_queso_fresco")
    print ("2. dias_maduracion")
    print ("3. costo_queso_madurado")
    print ("4. costo_porcion_madurado ")
    seleccion = int(input ("Por favor seleccione una de las siguientes opciones: "))
    match seleccion:
        case 1:
            costo_leche = float(input("Por favor indique el costo de leche utilizada: "))
            cantidad_leche = float(input("Por favor indique la cantidad de leche utilizada: "))
            costos_adicionales = float(input("Por favor indique los costos adicionales: "))
            print ("el costo del queso fresco es", end=" ")
            print (c.calcular_costo_queso_fresco (costo_leche, cantidad_leche, costos_adicionales), end=" ")
            print ("Pesos")
            consola () 
        case 2:
            cantidad_leche = float(input("Por favor indique la cantidad de leche utilizada: "))
            temperatura_almacenamiento = float(input("Por favor la temperatura de almacenamiento: "))
            humedad_relativa = float(input("Por favor la humedad relativa: "))
            print ("los dias de maduracion equivale a", end= " ")
            print (c.calcular_dias_maduracion(cantidad_leche, temperatura_almacenamiento, humedad_relativa), end=" ")
            print ("dias")
            consola () 
        case 3:
            costo_leche = float(input("Por favor indique el costo de leche utilizada: "))
            cantidad_leche = float(input("Por favor indique la cantidad de leche utilizada: "))
            costos_adicionales = float(input("Por favor los costos adicionales: "))
            costo_almacenamiento = float(input("Por favor los coostos de almacenamiento: "))
            temperatura_almacenamiento = float(input("Por favor la temperatura de almacenamiento: "))
            humedad_relativa = float(input("Por favor la humedad relativa: "))
            print ("el costo del queso maduro es de", end= " ")
            print (c.calcular_costo_queso_madurado(costo_leche, cantidad_leche, costos_adicionales, costo_almacenamiento, temperatura_almacenamiento, humedad_relativa), end=" ")
            print ("Pesos")
            consola ()
        case 4:
            costo_leche = float(input("Por favor indique el costo de leche utilizada: "))
            cantidad_leche = float(input("Por favor indique la cantidad de leche utilizada: "))
            costos_adicionales = float(input("Por favor los costos adicionales: "))
            costo_almacenamiento = float(input("Por favor los coostos de almacenamiento: "))
            temperatura_almacenamiento = float(input("Por favor la temperatura de almacenamiento: "))
            humedad_relativa = float(input("Por favor la humedad relativa: "))
            angulo_corte = float(input("Por favor el angulo de corte: "))
            print ("la distancia media equivale a", end= " ")
            print (c.calcular_costo_porcion_madurado(costo_leche, cantidad_leche, costos_adicionales, costo_almacenamiento, temperatura_almacenamiento, humedad_relativa, angulo_corte), end=" ")
            print ("metros")
            consola ()

consola ()